name: publish

on:
  pull_request:
    types: closed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && !contains(github.event.pull_request.labels.*.name, 'dependencies') && !contains(github.event.pull_request.labels.*.name, 'no publish')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/master
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --ignore-scripts
      # - run: npm run build
      # - run: npm run test
      - name: version_and_publish
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm version major
          npm publish
          git push gh-origin HEAD:master --follow-tags
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.LH_GITHUB_ADMIN_TOKEN }}